config/routes.rb
Rails.application.routes.draw do
  # users routes
  root "users#new"
  post "/users" => "users#create"
  delete "/users/:user_id" => "users#destroy"
  get "/users/:user_id/edit" => "users#edit"
  put "/users/:user_id" => "users#update"
  get "/about" => "users#about"

  # sessions routes
  post "/sessions" => "sessions#create"
  delete "/sessions/:id" => "sessions#destroy"

  # scripts routes
  get "/scripts" => "scripts#index"
  post "/scripts/gen" => "scripts#generate"
  get "/public" => "scripts#download"

  # admins routes
  get "/admins/:id" => "admins#show"
  get "/access/:id/allow" => "admins#allow"
  get "/access/:id/deny" => "admins#deny"

  # unknown routes
  get "*unknown_route", to: redirect("/")

end

app/models/dojo.rb
class Dojo < ActiveRecord::Base
	has_many :users, dependent: :delete_all
	has_many :admins, dependent: :delete_all

	validates :name, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :dojo
	has_one :admin, dependent: :delete

  has_secure_password
	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, presence: true, length: {minimum: 2}
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format:{with: email_regex}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_logged_in, only: [:new]
  before_action :user_authorized, only: [:edit]

  def new
    @dojos = Dojo.all
    # render "new.html.erb"
  end

  def about
  end

  def create
    # admin user registration
    if secret_params[:password] != ''
      key = SecretKey.last
      # valid admin password
      if key and key.authenticate(secret_params[:password])
        user = User.create(user_params.merge(dojo: Dojo.find(user_params[:dojo]), access: true))
        # successful admin user registration
        if user.valid?
          session[:user_id] = user.id
          Admin.create(user: user)
          redirect_to '/scripts'
        # failed admin user registration
        else
          flash[:msgs] = user.errors.full_messages
          redirect_to '/'
        end
      # invalid admin password
      else
        flash[:msgs] = ['Invalid admin password']
        redirect_to '/'
      end
    # student user registration
    else
      user = User.create(user_params.merge(dojo: Dojo.find(user_params[:dojo]), access: false))
      # successful student user registration
      if user.valid?
        session[:user_id] = user.id
        redirect_to '/scripts'
      # failed student user registration
      else
        flash[:msgs] = user.errors.full_messages
        redirect_to '/'
      end
    end
  end

  def destroy
    User.destroy(params[:user_id])
    redirect_to :back
  end

  def edit
    @current_user = current_user
    @dojos = Dojo.all
    # render "edit.html.erb"
  end

  def update
    user = User.update(params[:user_id], user_update_params.merge(dojo: Dojo.find(user_update_params[:dojo])))

    if user.valid?
      flash[:update] = ["#{user_update_params[:first_name]} was successfully updated..."]
    else
      flash[:msgs] = user.errors.full_messages
    end

    redirect_to :back
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :dojo)
    end

    def secret_params
      params.require(:secret_key).permit(:password)
    end

    def user_update_params
      params.require(:user).permit(:first_name, :last_name, :email, :dojo)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.html.erb
<div class="row">
	<h4>About</h4>
	<p>Turbo Deployments aims to simplify the deployment process for Coding Dojo students in the following stacks: Python Django, MEAN, and Ruby on Rails. By generating a script file, Turbo Deployments significantly decreases deployment time and guarantees a successful launch every time.</p>
</div>

<div class="row">
	<p class="bold">Technologies:</p>
	<div class="col s9 m12 l12">
		<img src="assets/css.png" class="tech-icon">
		<img src="assets/html.png" class="tech-icon">
		<img src="assets/javascript.png" class="tech-icon">
		<img src="assets/jquery.png" class="tech-icon">
		<img src="assets/materialize.png" class="tech-icon">
		<img src="assets/ruby.png" class="tech-icon">
		<img src="assets/rails.jpg" id="rails-icon">
		<img src="assets/bash.png" class="tech-icon black_border">
	</div>
</div>

<div class="row">
	<h4>Meet the Team</h4>
	<p>We are a diverse team of Coding Dojo Dallas students.</p>
</div>

<div class="row center-align">
	<!-- MD RAHAMAN -->
	<div class="profile col s12 m3 l3">
		<img class="team-pic" src="assets/md.jpg">
		<div class="contact-div">
			<h5>Md Rahaman</h5>
			<!-- Icons -->
			<div id=icons>
				<a href="mailto:soikatesc@gmail.com" class="fa fa-envelope contact-icon" target = "_blank"></a>
				<a href="https://www.linkedin.com/in/md-rahaman" class="fa fa-linkedin contact-icon" target = "_blank"></a>
				<a href="https://github.com/soikatesc" class="fa fa-github contact-icon" target = "_blank"></a>
			</div>
		</div>
		<div class="row">
			<p>Md has an electrical engineering background and decided to study at Coding Dojo to become a full stack developer. He loves to play cricket and his favorite team is Bangladesh.</p>
		</div>
	</div>

	<!-- ANDY LI -->
	<div class="profile col s12 m3 l3">
		<img class="team-pic" src="assets/andy.jpg">
		<div class="contact-div">
			<h5>Andy Li</h5>
			<!-- Icons -->
			<div id=icons>
				<a href="mailto:iandyli@gmail.com" class="fa fa-envelope contact-icon" target = "_blank"></a>
				<a href="https://www.linkedin.com/in/iliandy" class="fa fa-linkedin contact-icon" target = "_blank"></a>
				<a href="https://github.com/iliandy" class="fa fa-github contact-icon" target = "_blank"></a>
			</div>
		</div>
		<div class="row">
			<p>Andy has a BS in electrical engineering and applied math. He loves problem solving and his favorite language is Python. In his spare time, Andy participates in endurance events and other outdoor activities.</p>
		</div>
	</div>

	<!-- PATSY -->
	<div class="col s12 m3 l3">
		<img class="team-pic" src="assets/patsy.jpg">
		<div class="contact-div">
			<h5>Patsy Pineda</h5>
			<!-- Icons -->
			<div id=icons>
				<a href="mailto:patsyp014@gmail.com" class="fa fa-envelope contact-icon" target = "_blank"></a>
				<a href="https://www.linkedin.com/in/patsy-pineda-555837a5" class="fa fa-linkedin contact-icon" target = "_blank"></a>
				<a href="https://github.com/patsyp" class="fa fa-github contact-icon" target = "_blank"></a>
			</div>
		</div>
		<div class="row">
			<p>Patsy majored in English, but her enthusiasm for figuring out how things work made her discover the world of coding. When she is not studying at the Dojo, she is playing at the park with her dog.</p>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h4>Edit <%= @current_user.first_name %>'s Profile</h4>

<form action="/users/<%= @current_user.id %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">
  <div class="row">
    <div class="input-field col s12 m4 l4">
      <i class="material-icons prefix">person_outline</i>
      <label class="active" for="first_name">First Name:</label>
      <input id="first_name" type="text" name="user[first_name]" value="<%= @current_user.first_name %>">
    </div>
    <div class="input-field col s12 m4 l4">
      <i class="material-icons prefix">person</i>
      <label class="active" for="last_name">Last Name:</label>
      <input id="last_name" type="text" name="user[last_name]" value="<%= @current_user.last_name %>">
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12 m8 l8">
      <i class="material-icons prefix">mail_outline</i>
      <label class="active" for="email">E-mail:</label>
      <input id="email" type="text" name="user[email]" value="<%= @current_user.email %>">
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12 m8 l8">
      <i class="material-icons prefix">location_city</i>
      <select name="user[dojo]">
      <% @dojos.each do |dojo| %>
        <option <%= "selected" if dojo.id == @current_user.dojo.id %> value="<%= dojo.id %>"><%= dojo.name %></option>
      <% end %>
      </select>
    </div>
  </div>

  <button class="btn waves-effect waves-light green darken-4" type="submit" name="action">Update User
    <i class="material-icons right">send</i>
  </button>
</form>

<div class="blue-text">
  <% if flash[:update] %>
    <% flash[:update].each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<h3>Welcome!</h3>
<div class="row">
	<div class="col s12">
		<ul class="tabs">
			<li class="tab col s6 m2 l2"><a class="green-text" href="#login">Login</a></li>
			<% if flash[:msgs] && flash[:msgs] != ["Invalid login credentials"] %>
				<li class="tab col s6 m2 l2"><a class="green-text active" href="#register">Register</a></li>
			<% else %>
				<li class="tab col s6 m2 l2"><a class="green-text" href="#register">Register</a></li>
			<% end %>
      <div class="indicator green"></div>
		</ul>
	</div>

  <!-- user login -->
	<div id="login" class="col s12">
    <form action="/sessions" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="row">
        <div class="input-field col s12 m4 l4">
          <i class="material-icons prefix">mail_outline</i>
          <label for="login_email">E-mail:</label>
          <input id="login_email" type="text" name="login[email]">
        </div>

        <div class="input-field col s12 m4 l4">
          <i class="material-icons prefix">lock_outline</i>
          <label for="login_pass">Password:</label>
          <input id="login_pass" type="password" name="login[password]">
        </div>
      </div>

      <button class="btn waves-effect waves-light green darken-4" type="submit" name="action">Login User
        <i class="material-icons right">send</i>
      </button>
    </form>
	</div>

  <!-- user registration -->
	<div id="register" class="col s12">
    <form action="/users" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="row">
        <div class="input-field col s12 m4 l4">
          <i class="material-icons prefix">person_outline</i>
          <label for="first_name">First Name:</label>
          <input id="first_name" type="text" name="user[first_name]">
        </div>
        <div class="input-field col s12 m4 l4">
          <i class="material-icons prefix">person</i>
          <label for="last_name">Last Name:</label>
          <input id="last_name" type="text" name="user[last_name]">
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12 m8 l8">
          <i class="material-icons prefix">mail_outline</i>
          <label for="email">E-mail:</label>
          <input id="email" type="text" name="user[email]">
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12 m4 l4">
          <i class="material-icons prefix">lock_outline</i>
          <label for="password">Password:</label>
          <input id="password" type="password" name="user[password]">
        </div>
        <div class="input-field col s12 m4 l4">
          <i class="material-icons prefix">lock</i>
          <label for="password_conf">Password Confirmation:</label>
          <input id="password_conf" type="password" name="user[password_confirmation]">
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12 m8 l8">
          <i class="material-icons prefix">domain</i>
          <select name="user[dojo]">
            <% @dojos.each do |dojo| %>
            <option <%= "selected" if dojo.name == "Coding Dojo Dallas" %> value="<%= dojo.id %>"><%= dojo.name %></option>
            <% end %>
          </select>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12 m8 l8">
          <input type="checkbox" id="incs" >
          <label for="incs">Instructor</label>
        </div>
      </div>
      <div class="row" style="display:none;" id="ins-div">
        <div class="input-field col s8">
          <i class="material-icons prefix">vpn_key</i>
          <label for="secret_key">Admin Password:</label>
          <input id="secret_key" type="password" name="secret_key[password]">
        </div>
      </div>

      <button class="btn waves-effect waves-light green darken-4" type="submit" name="action">Register User
        <i class="material-icons right">send</i>
      </button>
    </form>

	</div>
</div>

app/views/users/scripts.html.erb
<% if @admin_ids.include? @current_user.id %>
| <a href="admins/<%= @current_user.id %>">Admin Dashboard</a>
<% end %>

<h3>Hi <%= @current_user.first_name %></h3>

<p>Select deployment script to generate</p>
<form class="" action="index.html" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="row">
    <div class="input-field col s8">
      <select name="stack">
        <option>Python</option>
        <option>MEAN</option>
        <option>Ruby</option>
      </select>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s8">
      <label>Project Directory Name: </label>
      <input type="text" name="proj_dir">
    </div>
  </div>

  <div class="row">
    <div class="input-field col s8">
      <label>GitHub Repo URL: </label>
      <input type="text" name="github_repo_url">
    </div>
  </div>

  <div class="row">
    <div class="input-field col s8">
      <label>AWS Server IP address: </label>
      <input type="password" name="server_ip">
    </div>
  </div>

  <button class="btn waves-effect waves-light" type="submit" name="action">Generate Script
    <i class="material-icons right">send</i>
  </button>
</form>